//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesignModern
{
    using System;
    using System.Collections.Generic;
    
    public partial class client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public client()
        {
            this.commande = new HashSet<commande>();
        }
    
        public int numC { get; set; }
        public int numTypeClient { get; set; }
        public string nomC { get; set; }
        public string prenomC { get; set; }
        public string adresseC { get; set; }
        public string cpC { get; set; }
        public string villeC { get; set; }
        public string paysC { get; set; }
        public string telC { get; set; }
        public string emailC { get; set; }
        public string loginC { get; set; }
        public string mdpC { get; set; }
    
        public virtual type_de_client type_de_client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<commande> commande { get; set; }
    }
}
