//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesignModern
{
    using System;
    using System.Collections.Generic;
    
    public partial class commande
    {
        public int numCmd { get; set; }
        public int numC { get; set; }
        public int idGarage { get; set; }
        public Nullable<System.DateTime> dateLivraisonCmd { get; set; }
        public Nullable<System.DateTime> dateCmd { get; set; }
        public string etatCmd { get; set; }
    
        public virtual client client { get; set; }
        public virtual garage garage { get; set; }
    }
}
