//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesignModern
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class motoristaDbContext : DbContext
    {
        public motoristaDbContext()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<client> client { get; set; }
        public virtual DbSet<commande> commande { get; set; }
        public virtual DbSet<garage> garage { get; set; }
        public virtual DbSet<marque> marque { get; set; }
        public virtual DbSet<modele> modele { get; set; }
        public virtual DbSet<type_de_client> type_de_client { get; set; }
        public virtual DbSet<type_de_garage> type_de_garage { get; set; }
        public virtual DbSet<type_de_voiture> type_de_voiture { get; set; }
        public virtual DbSet<voiture> voiture { get; set; }
    }
}
